#!/usr/bin/env bash
# Check every external link the import sandbox could not reach.
# Prints an HTTP status (000 = no connection) and the URL; anything 4xx/5xx/000 needs a look.
while read -r u; do
  code=$(curl -sS -o /dev/null -L -A 'Mozilla/5.0' --max-time 20 -w '%{http_code}' "$u" 2>/dev/null)
  printf '%s\t%s\n' "$code" "$u"
done <<'EOF'
http://Coolors.co
http://Unsplash.com
http://draw.io
http://planning.md
http://stackedit.io/
https://ai.google.dev/gemini-api/docs/prompting-intro
https://anchoreum.com
https://api-docs.deepseek.com/
https://artofproblemsolving.com/store/list/all-products
https://atmamani.github.io/projects/math/math-practical-odyssey-1/
https://barschazki.com/
https://blog.google/outreach-initiatives/education/google-ai-literacy-tools-2025/
https://carrd.co
https://code.visualstudio.com/docs/languages/polyglot
https://code.visualstudio.com/download
https://colab.research.google.com/
https://colab.research.google.com/drive/12t88COQSHkejPvinQh-pflc8STui2d2U?usp=sharing
https://colab.research.google.com/drive/135fjfXmyhwmh_yfTSi9U0Ai8pNHAELSU?usp=sharing
https://colab.research.google.com/drive/14RpqlLqCWD4TrICljFePm6MkrI3-akX6?usp=sharing
https://colab.research.google.com/drive/17VJVRy8p8lNz-AAFh3Si2mNoZbBUTCxQ?usp=sharing
https://colab.research.google.com/drive/1BOrH2LY3K5ycjyWP4hxLiW0P72gVenbG?usp=sharing
https://colab.research.google.com/drive/1Bwl0MtQYMpsJbQOy6uB2cgdXNyKUqZTS?usp=sharing
https://colab.research.google.com/drive/1Fb1G5Y0B3YLrhNsSh6srIq7VjPzv3hyE?usp=sharing
https://colab.research.google.com/drive/1IEfHkflNdG77fVYItyHWBs6HdyZZ7B2Y?usp=sharing
https://colab.research.google.com/drive/1MEqORIwrvNGSeW_afIRn4vlh-r0n9GbK?usp=sharing
https://colab.research.google.com/drive/1PNJPSxzZHbaymoigaee2Prk9_2srgcP7?usp=sharing
https://colab.research.google.com/drive/1RILVUXDDHPpJyRONq_2vbqq4Z7owRpqI?usp=sharing
https://colab.research.google.com/drive/1YY7Mc5rpogfd4zvOKDgNobwif6NLcLMl?usp=sharing
https://colab.research.google.com/drive/1ZkYYUsMAfDMSDYSGN2k5loFSWysBa-9i?usp=sharing
https://colab.research.google.com/drive/1aNCH63UW8Lp3lzEsX30VrNhQBkP7K8q6?usp=sharing
https://colab.research.google.com/drive/1awUANI0A1-pl3dGOJlwEUJ2g2Sh1JFJ5?usp=sharing
https://colab.research.google.com/drive/1cIWvFywOTPm0COk8649E1QesVg4QYpcl?usp=sharing
https://colab.research.google.com/drive/1hr-GDe3yw8EqAkVn7EgKsEFuBdulRtZi?usp=sharing
https://colab.research.google.com/drive/1hyAlMxwqy-Tc5zBPz7Vm1aCBJ1CK2YTo?usp=sharing
https://colab.research.google.com/drive/1iBUbw2NYNO0Bbia-nQDao69S0tF16huu?usp=sharing
https://colab.research.google.com/drive/1l9hV9KXMgXf6gHgySURrxIlOU0xLnzWx?usp=sharing
https://colab.research.google.com/drive/1ozDyE6-9orWFf4-IWcYXDToaD_HI0IDk?usp=sharing
https://colab.research.google.com/drive/1u7yZM2IZbi98H6GGYE1hxIsbmM5IGjyl?usp=sharing
https://colab.research.google.com/drive/1z1tLteudEYmUBeQPa04xqmxIgPs85qWu?usp=sharing
https://colab.research.google.com/github/jonkrohn/ML-foundations/blob/master/notebooks/5-probability.ipynb#scrollTo=HDE74CXX5ChI
https://cor.inquirygroup.org/videos/
https://creativecommons.org/
https://creativecommons.org/licenses/
https://creativecommons.org/network/
https://csharpplayersguide.com
https://cssgridgarden.com
https://cssgridgarden.com/
https://deepmind.google/blog/facts-grounding-a-new-benchmark-for-evaluating-the-factuality-of-large-language-models/
https://developer.mozilla.org/en-US/
https://developer.mozilla.org/en-US/blog/color-models-humans-devices/
https://developer.mozilla.org/en-US/curriculum/
https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics
https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics
https://developer.mozilla.org/en-US/docs/Learn/HTML
https://developer.mozilla.org/en-US/docs/Learn_web_development
https://developer.mozilla.org/en-US/docs/Web/HTML
https://deweydex.github.io/AIML_WA/
https://deweydex.github.io/WADB_Tutorials/
https://deweydex.github.io/WADB_Tutorials/#templates
https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site
https://docs.github.com/en/pages/quickstart
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll
https://docs.python.org/3/tutorial/datastructures.html
https://dotnet.microsoft.com/en-us/platform/try-dotnet
https://drive.google.com/drive/folders/16Bz6coMwbUoDRcGf0YDKx-LD3TGtUxeT?usp=sharing
https://drive.google.com/drive/folders/1dibQOpgwlpSpJU7l-uR6bGy7D0wUMHWe?usp=sharing
https://drive.google.com/drive/folders/1uqqf3PgZv7KjqGGVwclC5-OtXE1fuYRk?usp=sharing
https://drive.google.com/file/d/142hGZ0jp4Ch222iV3RBTxRRnzzNEWiFt/view?usp=sharing
https://drive.google.com/file/d/1VfD9iq77G-XyRrpzd5nC5M8LfVQOjnsY/view?usp=sharing
https://drive.google.com/file/d/1afTDSqAwoy4tExAnKUTqfsjAvxfs5x-6/view?usp=sharing
https://drive.google.com/file/d/1i0CFLTwQjzXxcDtNhcS9xcjyuB5SinQK/view?usp=share_link
https://edabit.com/challenges/csharp
https://en.wikipedia.org/wiki/CSS
https://en.wikipedia.org/wiki/HTML
https://flexboxfroggy.com
https://flexboxfroggy.com/
https://forms.office.com/e/huXkP8EbkC
https://garyliang.substack.com/p/google-learnlm-technical-paper
https://github.com/deweydex
https://github.com/deweydex/
https://glitch.com/
https://gohugo.io/
https://greenteapress.com/wp/think-python-2e/
https://inventwithpython.com
https://iscontent.byu.edu/Canvas/MATH-110/MATH-110-M004/HTML/0_PlacementH5P.html
https://jsaaron.carrd.co/#
https://jsaaron.com
https://learn.microsoft.com/en-us/collections/yz26f8y64n7k07
https://machinelearningmastery.com/implement-backpropagation-algorithm-scratch-python/#
https://markdownonline.org
https://mathsaustralia.com.au/placement-tests/placement-tests/
https://meta.wikimedia.org/
https://nolanlawson.com/2023/12/02/lets-learn-how-modern-javascript-frameworks-work-by-building-one/
https://onecompiler.com/csharp
https://ourworldindata.org
https://ourworldindata.org/
https://pages.github.com
https://paper.co
https://platform.openai.com/docs/guides/prompt-engineering
https://playground.tensorflow.org/
https://pythonz2h.com
https://realpython.com/python-complex-numbers/
https://research.google/blog/learn-your-way-reimagining-textbooks-with-generative-ai/
https://scottlilly.com/learn-c-by-building-a-simple-rpg-index/
https://signal.org/
https://signal.org/blog/
https://sqltoerdiagram.com
https://stackedit.io/app#
https://teams.microsoft.com/l/channel/19%3AjGlwVqtAl-zrkb3tZFkhPe2mOYo7AURkFylvSCjgvCk1%40thread.tacv2/General?groupId=a5fa6cb9-195f-4b5c-a8c5-71df0a40e9a6&tenantId=3ed6c8f5-4c16-44ad-9eed-60f851834a84
https://teams.microsoft.com/l/team/19%3AcF-aggvE1Scbs1qqZbYJ36OmioVRbS3GKNzFLfgv7oI1%40thread.tacv2/conversations?groupId=07c64daa-a9bf-4733-acb7-5921b3833eeb&tenantId=3ed6c8f5-4c16-44ad-9eed-60f851834a84
https://thecrashcourse.com/topic/medialiteracy/
https://timothyprojectgig.github.io/JB_Math_Textbook/ProbStat/ProbIntro/prob.html
https://v2.scrimba.com/learn-typescript-c03c
https://www.3blue1brown.com/?topic=neural-networks
https://www.3blue1brown.com/topics/linear-algebra
https://www.3blue1brown.com/topics/neural-networks
https://www.audiolabs-erlangen.de/resources/MIR/PCP/PCP_06_complex.html
https://www.codecademy.com/article/csharp-go-off-platform
https://www.codecademy.com/article/what-is-net
https://www.codecademy.com/catalog/language/html-css
https://www.codecademy.com/learn/learn-c-sharp
https://www.codecademy.com/learn/learn-sql
https://www.codecademy.com/learn/learn-typescript
https://www.codechef.com/practice/python
https://www.edupyter.net/en/
https://www.eff.org/
https://www.eff.org/issues
https://www.freecodecamp.org/
https://www.freecodecamp.org/learn/college-algebra-with-python/#build-three-math-games-project
https://www.freecodecamp.org/learn/foundational-c-sharp-with-microsoft/
https://www.freecodecamp.org/learn/the-odin-project/
https://www.freecodecamp.org/news/connect-python-with-sql/
https://www.freecodecamp.org/news/freecodecamp-foundational-math-curriculum/
https://www.freecodecamp.org/news/html-and-css-course/
https://www.freecodecamp.org/news/learn-college-calculus-in-free-course/
https://www.freecodecamp.org/news/the-most-popular-coding-challenge-websites/
https://www.freecodecamp.org/news/unit-circle-chart-and-trig-calculator/
https://www.inquirygroup.org
https://www.jetbrains.com/pycharm/
https://www.kaggle.com/learn/intro-to-machine-learning
https://www.khanacademy.org/join/BDBED472
https://www.khanacademy.org/join/MAR9BPAP
https://www.khanacademy.org/python-program/map-making-group-coding/4910017609646080
https://www.khanacademy.org/python-program/reverse/6465531776253952
https://www.khanacademy.org/python-program/slicing/4824728708497408
https://www.learningfromexamples.com/p/what-academics-get-wrong
https://www.library.unsw.edu.au/using-the-library/information-resources/primary-and-secondary-sources
https://www.linkedin.com/learning-login/share?account=237718738&forceAccount=true&redirect=https%3A%2F%2Fwww%2Elinkedin%2Ecom%2Flearning%2Fpaths%2Fdublin-and-dun-laoghaire-etb-ddletb-foundations-of-ai-for-business%3FshareId=8dd6258c-dfdb-4395-a534-54c07171883b
https://www.markdownguide.org
https://www.markdownguide.org/basic-syntax/
https://www.markdowntutorial.com
https://www.maths.ox.ac.uk/study-here/undergraduate-study/maths-admissions-test
https://www.monroeu.edu/sites/default/files/documents/2020/01/31/placementexamreview.pdf
https://www.mozilla.org/
https://www.mozilla.org/en-US/about/manifesto/
https://www.programiz.com/csharp-programming/online-compiler/
https://www.py4e.com/book
https://www.sql-easy.com/
https://www.theodinproject.com/paths/foundations/courses/foundations
https://www.tudublin.ie/media/website/study/admissions/documents/MCT-exam-Easter2019-exam-paper.pdf
https://www.tudublin.ie/media/website/study/undergraduate/entry-pathways/documents/MCT-August-2018-Exam-paper.pdf
https://www.tudublin.ie/study/undergraduate/cao/entry-requirements/maths-competency-test/
https://www.tutorialsteacher.com/csharp
https://www.w3.org/Style/CSS/specs.en.html
https://www.w3schools.com/sql/
https://www.webwise.ie/teachers/digital_literacy/
https://www.wikimedia.org/
https://www.youtube.com/playlist?list=PLdo4fOcmZ0oULFjxrOagaERVAMbmG20Xe
https://www.youtube.com/playlist?list=PLiaHhY2iBX9g6KIvZ_703G3KJXapKkNaF
https://www.youtube.com/watch?v=8idr1WZ1A7Q
https://www.youtube.com/watch?v=G43vl3RKN5s
https://www.youtube.com/watch?v=HZGCoVF3YvM&list=PLiAulSm0XXgvCGe63mrAkda9UQ9478YQv
https://www.youtube.com/watch?v=LPZh9BOjkQs&vl=en
https://www.youtube.com/watch?v=SmZmBKc7Lrs
https://www.youtube.com/watch?v=WUvTyaaNkzM
https://www.youtube.com/watch?v=aircAruvnKk&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi
https://www.youtube.com/watch?v=bxe2T-V8XRs&list=PLiaHhY2iBX9hdHaRr6b7XevZtgZRa1PoU
https://www.youtube.com/watch?v=lgUIx75fJ_E&list=PLFgjYYTq6xyhtVK6VzLiFe3pmBu-XSNlX
https://www.youtube.com/watch?v=xQlD5uYwYEs
https://www3.cs.stonybrook.edu/~pfodor/courses/CSE316/L03-HTML_CSS.pdf
https://youtu.be/6YzrVUVO9M0
https://youtu.be/GkiITbgu0V0
https://youtu.be/XTcP4oo4JI4
EOF
